import { authorizeApi,apiError,isResponse } from "../../api-helpers";
import { validateProjectInput } from "../../../../projects/project-contract";
export const dynamic="force-dynamic";

export async function GET(_request:Request,{params}:{params:Promise<{id:string}>}){const context=await authorizeApi("project.view");if(isResponse(context))return context;const{id}=await params;const{getProject}=await import("../../../../../db/projects");const project=await getProject(id);if(!project)return apiError(404,"PROJECT_NOT_FOUND","Project was not found.",context.correlationId,context.timestamp);return Response.json({data:project,meta:{correlationId:context.correlationId,timestamp:context.timestamp}},{headers:{"cache-control":"no-store"}});}

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const context=await authorizeApi("project.edit");if(isResponse(context))return context;const{id}=await params;let body:unknown;try{body=await request.json();}catch{return apiError(400,"INVALID_JSON","Request body must be valid JSON.",context.correlationId,context.timestamp);}const source=body&&typeof body==="object"?body as Record<string,unknown>:{};const validation=validateProjectInput(source);if(!validation.ok)return apiError(422,"VALIDATION_FAILED","Review the highlighted fields.",context.correlationId,context.timestamp,validation.details);const version=Number(source.version);if(!Number.isInteger(version)||version<1)return apiError(422,"VERSION_REQUIRED","A valid record version is required.",context.correlationId,context.timestamp,{version:"Refresh and try again."});try{const{updateProject}=await import("../../../../../db/projects");const result=await updateProject(id,validation.value,version,context.principal.user.userId,context.correlationId);if(result.kind==="not_found")return apiError(404,"PROJECT_NOT_FOUND","Project was not found.",context.correlationId,context.timestamp);if(result.kind==="conflict")return apiError(409,"UPDATE_CONFLICT","This Project changed after you opened it. Refresh and try again.",context.correlationId,context.timestamp);if(result.kind==="invalid_product")return apiError(422,"INVALID_PARENT_PRODUCT","Select an active parent Product.",context.correlationId,context.timestamp,{productId:"The selected Product is unavailable."});return Response.json({data:result.project,meta:{correlationId:context.correlationId,timestamp:context.timestamp}},{headers:{"cache-control":"no-store"}});}catch{return apiError(409,"DUPLICATE_PROJECT","A Project with this code already exists.",context.correlationId,context.timestamp);}}

export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const context=await authorizeApi("project.archive");if(isResponse(context))return context;const{id}=await params;let body:unknown;try{body=await request.json();}catch{return apiError(400,"INVALID_JSON","Request body must be valid JSON.",context.correlationId,context.timestamp);}const source=body&&typeof body==="object"?body as Record<string,unknown>:{};const reason=typeof source.reason==="string"?source.reason.trim():"",version=Number(source.version);if(reason.length<5)return apiError(422,"VALIDATION_FAILED","An archive reason is required.",context.correlationId,context.timestamp,{reason:"Provide at least five characters."});const{archiveProject}=await import("../../../../../db/projects");const result=await archiveProject(id,version,reason,context.principal.user.userId,context.correlationId);if(result.kind==="not_found")return apiError(404,"PROJECT_NOT_FOUND","Project was not found.",context.correlationId,context.timestamp);if(result.kind==="conflict")return apiError(409,"UPDATE_CONFLICT","This Project changed after you opened it. Refresh and try again.",context.correlationId,context.timestamp);return new Response(null,{status:204});}
