import type { ConnectionTestResult,EngineeringDeliveryProvider } from "./engineering-delivery-provider";
type Config={organization:string;authType:"ENTRA_APPLICATION"|"PAT";credential:string};
type AzureList<T>={count:number;value:T[]};

export class AzureDevOpsProvider implements EngineeringDeliveryProvider{
 constructor(private readonly config:Config){}
 private async request<T>(path:string):Promise<T>{const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const authorization=this.config.authType==="PAT"?`Basic ${btoa(`:${this.config.credential}`)}`:`Bearer ${this.config.credential}`;const response=await fetch(`https://dev.azure.com/${encodeURIComponent(this.config.organization)}${path}`,{headers:{accept:"application/json",authorization},signal:controller.signal});if(!response.ok){const error=new Error(`Azure DevOps returned ${response.status}.`) as Error&{status?:number};error.status=response.status;throw error;}return await response.json() as T;}finally{clearTimeout(timeout);}}
 async testConnection():Promise<ConnectionTestResult>{const testedAt=new Date().toISOString();try{const projects=await this.getProjects();return{ok:true,authenticated:true,projectsVisible:projects.length,testedAt,message:`Connection succeeded. ${projects.length} Project${projects.length===1?"":"s"} visible.`};}catch(error){const status=(error as {status?:number}).status;const code=status===401?"AZURE_AUTHENTICATION_FAILED":status===403?"AZURE_PERMISSION_DENIED":status===429?"AZURE_RATE_LIMITED":error instanceof DOMException&&error.name==="AbortError"?"AZURE_TIMEOUT":"AZURE_API_FAILURE";return{ok:false,authenticated:false,projectsVisible:0,testedAt,errorCode:code,message:code==="AZURE_AUTHENTICATION_FAILED"?"Azure rejected the configured credential.":code==="AZURE_PERMISSION_DENIED"?"The credential does not have permission to read Azure Projects.":code==="AZURE_RATE_LIMITED"?"Azure rate-limited the request. Try again later.":code==="AZURE_TIMEOUT"?"Azure did not respond before the safe timeout.":"Azure DevOps could not be reached."};}}
 async getProjects(){const result=await this.request<AzureList<{id:string;name:string;description?:string;state:string;url:string}>>(`/_apis/projects?stateFilter=WellFormed&$top=100&api-version=7.1`);return result.value.map((p)=>({id:p.id,name:p.name,description:p.description??null,state:p.state,url:p.url}));}
 async getTeams():Promise<unknown[]>{throw new Error("Team discovery is delivered in Step 9.");}async getIterations():Promise<unknown[]>{throw new Error("Iteration retrieval is delivered in Step 11.");}async getCurrentSprint():Promise<null>{throw new Error("Sprint retrieval is delivered in Step 11.");}async getWorkItems():Promise<unknown[]>{throw new Error("Work-item retrieval is delivered in Step 10.");}async getWorkItem():Promise<null>{throw new Error("Work-item retrieval is delivered in Step 10.");}async getSprintMetrics():Promise<unknown>{throw new Error("Sprint metrics are delivered in Step 11.");}async getDevelopmentMetrics():Promise<unknown>{throw new Error("Development metrics are delivered in Step 10.");}
}
