"use client";

import { useEffect, useState } from "react";
import { azureNormalizedStates, azureNormalizedTypes, type AzureMappingEntryInput } from "./azure-mapping-contract";

type Connection = { id: string; name: string };

export function AzureMappingManager({ connection, canConfigure, onClose }: { connection: Connection; canConfigure: boolean; onClose: () => void }) {
  const [entries, setEntries] = useState<AzureMappingEntryInput[]>([]), [recommended, setRecommended] = useState<AzureMappingEntryInput[]>([]), [version, setVersion] = useState(1), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState("");
  useEffect(() => { void (async () => { try { const response = await fetch(`/api/v2/azure/connections/${connection.id}/mappings`), body = await response.json(); if (!response.ok) throw new Error(body.error?.message); setEntries(body.data.entries ?? []); setRecommended(body.data.recommendedEntries ?? []); setVersion(body.data.version); } catch (caught) { setError(caught instanceof Error ? caught.message : "Mappings could not be loaded."); } finally { setLoading(false); } })(); }, [connection.id]);
  const update = (index: number, patch: Partial<AzureMappingEntryInput>) => setEntries(current => current.map((entry, entryIndex) => entryIndex === index ? { ...entry, ...patch } : entry));
  const add = (mappingKind: "TYPE" | "STATE") => setEntries(current => [...current, { mappingKind, externalValue: "", normalizedValue: mappingKind === "TYPE" ? "STORY" : "IN_PROGRESS" }]);
  const save = async () => { setSaving(true); setError(""); setMessage(""); try { const response = await fetch(`/api/v2/azure/connections/${connection.id}/mappings`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ entries, version }) }), body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Mappings could not be saved."); setEntries(body.data.entries ?? []); setVersion(body.data.version); setMessage("Azure normalization mappings saved."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Mappings could not be saved."); } finally { setSaving(false); } };
  return <div className="dialog-backdrop"><div className="product-dialog mapping-dialog" role="dialog" aria-modal="true" aria-labelledby="azure-mapping-title"><div className="dialog-header"><div><span className="section-kicker">PROCESS NORMALIZATION</span><h2 id="azure-mapping-title">{connection.name}</h2></div><button onClick={onClose} aria-label="Close">×</button></div><div className="mapping-body"><div className="integration-guidance"><span>↔</span><div><strong>External values remain visible</strong><p>Map this organization&apos;s process terms to the governed Command Center model. Unmapped values are preserved and excluded from misleading completion calculations.</p></div></div>{message && <div className="success-banner" role="status">{message}</div>}{error && <div className="form-error" role="alert">{error}</div>}{loading ? <div className="module-state compact-state"><span className="loader" />Loading mappings…</div> : <><div className="mapping-toolbar"><strong>{entries.length} active mappings</strong>{canConfigure && <div><button className="secondary-action" onClick={() => setEntries(recommended.map(entry => ({ ...entry })))}>Use recommended set</button><button onClick={() => add("TYPE")}>+ Type</button><button onClick={() => add("STATE")}>+ State</button></div>}</div><div className="mapping-list">{entries.map((entry, index) => <article key={`${entry.mappingKind}:${index}`}><b>{entry.mappingKind}</b><input aria-label={`External value ${index + 1}`} value={entry.externalValue} disabled={!canConfigure} onChange={event => update(index, { externalValue: event.target.value })} placeholder="Azure value" /><span>→</span><select aria-label={`Normalized value ${index + 1}`} value={entry.normalizedValue} disabled={!canConfigure} onChange={event => update(index, { normalizedValue: event.target.value as AzureMappingEntryInput["normalizedValue"] })}>{(entry.mappingKind === "TYPE" ? azureNormalizedTypes : azureNormalizedStates).map(value => <option key={value}>{value}</option>)}</select>{canConfigure && <button aria-label={`Remove ${entry.externalValue || "mapping"}`} onClick={() => setEntries(current => current.filter((_, entryIndex) => entryIndex !== index))}>Remove</button>}</article>)}</div></>}</div><div className="dialog-actions"><button className="secondary-action" onClick={onClose}>{canConfigure ? "Cancel" : "Done"}</button>{canConfigure && <button className="primary-action" disabled={saving || loading} onClick={save}>{saving ? "Saving…" : "Save mappings"}</button>}</div></div></div>;
}
