export type ExternalProject={id:string;name:string;description:string|null;state:string;url:string};
export type ExternalTeam={id:string;name:string;description:string|null;url:string};
export type DevelopmentMetrics={totalItems:number;completedItems:number;activeItems:number;otherItems:number;progress:number;sourceRevision:string};
export type ExternalIteration={id:string;name:string;path:string;startDate:string|null;finishDate:string|null};export type SprintMetrics=ExternalIteration&{totalItems:number;completedItems:number;activeItems:number;progress:number;daysRemaining:number|null;health:string;sourceRevision:string};
export type ConnectionTestResult={ok:boolean;authenticated:boolean;projectsVisible:number;testedAt:string;errorCode?:string;message:string};
export type ExternalWorkItemRelation={relationType:string;targetExternalId:string};
export type ExternalWorkItem={externalId:string;externalRevision:string;externalType:string;externalState:string;parentExternalId:string|null;title:string;owner:string|null;storyPoints:number|null;remainingWork:number|null;blocked:boolean;blockedReason:string|null;iterationId:string|null;iterationPath:string|null;relations:ExternalWorkItemRelation[];sourceUrl:string;sourceChangedAt:string|null};
export type AdvancedWorkItemSource={items:ExternalWorkItem[];pagesRead:number;sourceRevision:string;retrievedAt:string;complete:boolean};
export interface EngineeringDeliveryProvider{testConnection():Promise<ConnectionTestResult>;getProjects():Promise<ExternalProject[]>;getTeams(projectId:string):Promise<ExternalTeam[]>;getIterations(projectId:string,teamId:string):Promise<ExternalIteration[]>;getCurrentSprint(projectId:string,teamId:string):Promise<ExternalIteration|null>;getWorkItems(projectId:string,ids:number[]):Promise<unknown[]>;getWorkItem(projectId:string,id:number):Promise<unknown|null>;getAdvancedWorkItems(projectId:string,teamId?:string|null):Promise<AdvancedWorkItemSource>;getSprintMetrics(projectId:string,teamId:string,iterationId:string):Promise<SprintMetrics>;getDevelopmentMetrics(projectId:string,teamId?:string|null):Promise<DevelopmentMetrics>;}
