"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import { defaultWeights,projectHealth,projectStatuses,releaseStatuses,signOffStatuses,stageKeys } from "./project-contract";
import { productPriorities } from "../products/product-contract";
import { ProjectOverview } from "./project-overview";

type Product={id:string;name:string;code:string};
type Project={id:string;businessId:string;name:string;code:string;productId:string;productName:string;productCode:string;description:string;objective:string;businessValue:string;scope:string;outOfScope:string;startDate:string|null;targetEndDate:string|null;actualEndDate:string|null;priority:string;status:string;health:string;overallProgress:number;requirementsProgress:number;designProgress:number;developmentProgress:number;qaProgress:number;uatProgress:number;signOffProgress:number;deploymentProgress:number;signOffStatus:string;releaseStatus:string;budgetAmount:number;budgetCurrency:string;market:string;customer:string;comments:string;weights:Record<string,number>;version:number};
const empty={name:"",code:"",productId:"",description:"",objective:"",businessValue:"",scope:"",outOfScope:"",startDate:"",targetEndDate:"",actualEndDate:"",priority:"Medium",status:"Active",health:"On Track",requirementsProgress:0,designProgress:0,developmentProgress:0,qaProgress:0,uatProgress:0,signOffProgress:0,deploymentProgress:0,signOffStatus:"Pending",releaseStatus:"Not Planned",budgetAmount:0,budgetCurrency:"USD",market:"",customer:"",comments:"",weights:{...defaultWeights}};

export function ProjectPortfolio({canCreate,canEdit}:{canCreate:boolean;canEdit:boolean}){
 const[items,setItems]=useState<Project[]>([]),[products,setProducts]=useState<Product[]>([]);const[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[success,setSuccess]=useState("");const[q,setQ]=useState(""),[productId,setProductId]=useState(""),[health,setHealth]=useState(""),[status,setStatus]=useState("");const[open,setOpen]=useState(false),[editing,setEditing]=useState<Project|null>(null),[form,setForm]=useState({...empty,weights:{...defaultWeights}}),[errors,setErrors]=useState<Record<string,string>>({}),[saving,setSaving]=useState(false);const[overviewId,setOverviewId]=useState<string|null>(null),[overview,setOverview]=useState<React.ComponentProps<typeof ProjectOverview>["overview"]>(null),[overviewLoading,setOverviewLoading]=useState(false),[overviewError,setOverviewError]=useState("");const first=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");const p=new URLSearchParams({pageSize:"50",sort:"name"});if(q.trim())p.set("q",q.trim());if(productId)p.set("productId",productId);if(health)p.set("health",health);if(status)p.set("status",status);try{const[r,pr]=await Promise.all([fetch(`/api/v1/projects?${p}`),fetch("/api/v1/products?pageSize=100&sort=name")]);const body=await r.json(),pb=await pr.json();if(!r.ok)throw new Error(body.error?.message??"Projects could not be loaded.");if(pr.ok)setProducts(pb.data??[]);setItems(body.data??[]);setTotal(body.meta?.total??0);}catch(c){setError(c instanceof Error?c.message:"Projects could not be loaded.");}finally{setLoading(false);}},[q,productId,health,status]);
 useEffect(()=>{const h=setTimeout(load,180);return()=>clearTimeout(h);},[load]);useEffect(()=>{if(open)setTimeout(()=>first.current?.focus(),0);},[open]);
 const change=(k:string,v:string|number)=>setForm(f=>({...f,[k]:v}));const weight=(k:string,v:number)=>setForm(f=>({...f,weights:{...f.weights,[k]:v}}));
 const create=()=>{setEditing(null);setForm({...empty,productId:products[0]?.id??"",weights:{...defaultWeights}});setErrors({});setOpen(true);};
 const edit=(p:Project)=>{setEditing(p);setForm({name:p.name,code:p.code,productId:p.productId,description:p.description,objective:p.objective,businessValue:p.businessValue,scope:p.scope,outOfScope:p.outOfScope,startDate:p.startDate??"",targetEndDate:p.targetEndDate??"",actualEndDate:p.actualEndDate??"",priority:p.priority,status:p.status,health:p.health,requirementsProgress:p.requirementsProgress,designProgress:p.designProgress,developmentProgress:p.developmentProgress,qaProgress:p.qaProgress,uatProgress:p.uatProgress,signOffProgress:p.signOffProgress,deploymentProgress:p.deploymentProgress,signOffStatus:p.signOffStatus,releaseStatus:p.releaseStatus,budgetAmount:p.budgetAmount,budgetCurrency:p.budgetCurrency,market:p.market,customer:p.customer,comments:p.comments,weights:{...defaultWeights,...p.weights}});setErrors({});setOpen(true);};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setErrors({});setError("");try{const r=await fetch(editing?`/api/v1/projects/${editing.id}`:"/api/v1/projects",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,...(editing?{version:editing.version}:{})})});const b=await r.json();if(!r.ok){setErrors(b.error?.validationDetails??{});throw new Error(b.error?.message??"The Project could not be saved.");}setOpen(false);setSuccess(editing?"Project updated.":"Project created.");await load();setTimeout(()=>setSuccess(""),3000);}catch(c){setError(c instanceof Error?c.message:"The Project could not be saved.");}finally{setSaving(false);}};
 const showOverview=async(id:string)=>{setOverviewId(id);setOverview(null);setOverviewError("");setOverviewLoading(true);try{const r=await fetch(`/api/v1/projects/${id}/overview`);const b=await r.json();if(!r.ok)throw new Error(b.error?.message??"The overview could not be loaded.");setOverview(b.data);}catch(c){setOverviewError(c instanceof Error?c.message:"The overview could not be loaded.");}finally{setOverviewLoading(false);}};
 const weightTotal=stageKeys.reduce((sum,k)=>sum+Number(form.weights[k]??0),0);
 return <section className="portfolio-module" aria-labelledby="project-list-title"><div className="portfolio-toolbar"><div><span className="section-kicker">PROJECT PORTFOLIO</span><h2 id="project-list-title">Projects <small>{total}</small></h2></div>{canCreate&&<button className="primary-action" onClick={create} disabled={!products.length}>+ New Project</button>}</div>{success&&<div className="success-banner" role="status">{success}</div>}<div className="filter-bar"><label className="search-field"><span className="sr-only">Search Projects</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, code or ID"/></label><label><span className="sr-only">Product</span><select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">All Products</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><span className="sr-only">Health</span><select value={health} onChange={e=>setHealth(e.target.value)}><option value="">All health</option>{projectHealth.map(v=><option key={v}>{v}</option>)}</select></label><label><span className="sr-only">Status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{projectStatuses.map(v=><option key={v}>{v}</option>)}</select></label></div>
 {loading?<div className="module-state" role="status"><span className="loader"/>Loading Projects…</div>:error&&!items.length?<div className="module-state error-state"><strong>Projects are unavailable</strong><p>{error}</p><button onClick={load}>Try again</button></div>:!items.length?<div className="module-state empty-state"><span>◇</span><strong>No Projects found</strong><p>{products.length?"Create a Project beneath an active Product.":"Create a Product before adding its first Project."}</p>{canCreate&&products.length>0&&<button onClick={create}>Create Project</button>}</div>:<div className="table-shell"><table className="portfolio-table"><thead><tr><th>Project</th><th>Product</th><th>Health</th><th>Status</th><th>Progress</th><th>Development</th><th>Target end</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td><button className="project-link" onClick={()=>showOverview(p.id)}><strong>{p.name}</strong><span>{p.businessId} · {p.code}</span></button></td><td>{p.productName}</td><td><span className={`health-badge health-${p.health.toLowerCase().replaceAll(" ","-")}`}>{p.health}</span></td><td><span className="neutral-badge">{p.status}</span></td><td><Progress value={p.overallProgress}/></td><td><Progress value={p.developmentProgress}/></td><td>{p.targetEndDate?new Date(`${p.targetEndDate}T00:00:00`).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"}):"—"}</td><td><button className="row-action" onClick={()=>showOverview(p.id)}>Open</button>{canEdit&&<button className="row-action" onClick={()=>edit(p)}>Edit</button>}</td></tr>)}</tbody></table></div>}
 {open&&<div className="dialog-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setOpen(false);}}><div className="product-dialog project-dialog" role="dialog" aria-modal="true" aria-labelledby="project-form-title"><form onSubmit={save}><div className="dialog-header"><div><span className="section-kicker">{editing?editing.businessId:"NEW INITIATIVE"}</span><h2 id="project-form-title">{editing?"Edit Project":"Create Project"}</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close">×</button></div><div className="form-grid">
 <Field label="Project name" error={errors.name} required><input ref={first} value={form.name} onChange={e=>change("name",e.target.value)}/></Field><Field label="Project code" error={errors.code} required><input value={form.code} onChange={e=>change("code",e.target.value.toUpperCase())}/></Field><Field label="Parent Product" error={errors.productId} required><select value={form.productId} onChange={e=>change("productId",e.target.value)}><option value="">Select Product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.code}</option>)}</select></Field><Field label="Priority"><select value={form.priority} onChange={e=>change("priority",e.target.value)}>{productPriorities.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Status"><select value={form.status} onChange={e=>change("status",e.target.value)}>{projectStatuses.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Health"><select value={form.health} onChange={e=>change("health",e.target.value)}>{projectHealth.map(v=><option key={v}>{v}</option>)}</select></Field>
 <Field label="Description" wide><textarea rows={2} value={form.description} onChange={e=>change("description",e.target.value)}/></Field><Field label="Objective" wide><textarea rows={2} value={form.objective} onChange={e=>change("objective",e.target.value)}/></Field><Field label="Business value" wide><textarea rows={2} value={form.businessValue} onChange={e=>change("businessValue",e.target.value)}/></Field><Field label="Scope" wide><textarea rows={2} value={form.scope} onChange={e=>change("scope",e.target.value)}/></Field><Field label="Out of scope" wide><textarea rows={2} value={form.outOfScope} onChange={e=>change("outOfScope",e.target.value)}/></Field>
 <Field label="Start date"><input type="date" value={form.startDate} onChange={e=>change("startDate",e.target.value)}/></Field><Field label="Target end" error={errors.targetEndDate}><input type="date" value={form.targetEndDate} onChange={e=>change("targetEndDate",e.target.value)}/></Field><Field label="Actual end"><input type="date" value={form.actualEndDate} onChange={e=>change("actualEndDate",e.target.value)}/></Field><Field label="Budget"><input type="number" min="0" value={form.budgetAmount} onChange={e=>change("budgetAmount",Number(e.target.value))}/></Field><Field label="Currency"><input maxLength={3} value={form.budgetCurrency} onChange={e=>change("budgetCurrency",e.target.value.toUpperCase())}/></Field><Field label="Market"><input value={form.market} onChange={e=>change("market",e.target.value)}/></Field><Field label="Customer"><input value={form.customer} onChange={e=>change("customer",e.target.value)}/></Field>
 <div className="wide stage-editor"><div className="stage-editor-heading"><div><strong>Stage progress &amp; weights</strong><span>Overall progress is calculated automatically.</span></div><b className={weightTotal===100?"total-ok":"total-error"}>{weightTotal}% weight</b></div><div className="stage-editor-grid">{stageKeys.map(k=><div key={k}><label><span>{label(k)} progress</span><input type="number" min="0" max="100" value={form[`${k}Progress` as keyof typeof form] as number} onChange={e=>change(`${k}Progress`,Number(e.target.value))}/></label><label><span>Weight</span><input type="number" min="0" max="100" value={form.weights[k]} onChange={e=>weight(k,Number(e.target.value))}/></label></div>)}</div>{errors.weights&&<small className="field-error">{errors.weights}</small>}</div>
 <Field label="Sign-off status"><select value={form.signOffStatus} onChange={e=>change("signOffStatus",e.target.value)}>{signOffStatuses.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Release status"><select value={form.releaseStatus} onChange={e=>change("releaseStatus",e.target.value)}>{releaseStatuses.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Comments" wide><textarea rows={2} value={form.comments} onChange={e=>change("comments",e.target.value)}/></Field></div>{error&&<div className="form-error" role="alert">{error}</div>}<div className="dialog-actions"><button type="button" className="secondary-action" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-action" disabled={saving||weightTotal!==100}>{saving?"Saving…":editing?"Save changes":"Create Project"}</button></div></form></div></div>}
 {overviewId&&<ProjectOverview overview={overview} loading={overviewLoading} error={overviewError} onClose={()=>setOverviewId(null)} onRetry={()=>showOverview(overviewId)} canEdit={canEdit} onEdit={()=>{const record=items.find(item=>item.id===overviewId);setOverviewId(null);if(record)edit(record);}}/>}
 </section>;
}
function Progress({value}:{value:number}){return <div className="table-progress"><span><i style={{width:`${value}%`}}/></span><b>{value}%</b></div>};
function Field({label,error,wide,required,children}:{label:string;error?:string;wide?:boolean;required?:boolean;children:React.ReactNode}){return <label className={wide?"field wide":"field"}><span>{label}{required&&<b aria-hidden="true"> *</b>}</span>{children}{error&&<small role="alert">{error}</small>}</label>}
const label=(value:string)=>value.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase());
