"use client";
import { useEffect, useRef } from "react";

type Project = { id:string;businessId:string;name:string;code:string;productName:string;productCode:string;description:string;objective:string;businessValue:string;scope:string;outOfScope:string;startDate:string|null;targetEndDate:string|null;actualEndDate:string|null;priority:string;status:string;health:string;overallProgress:number;signOffStatus:string;releaseStatus:string;budgetAmount:number;budgetCurrency:string;market:string;customer:string;updatedAt:string };
type Overview = { project:Project;stageProgress:Array<{stage:string;completion:number;weight:number;weightedContribution:number;source:string}>;delivery:{connected:boolean;provider:string|null;connectionName?:string;organization?:string;azureProjectName?:string;azureTeamName?:string|null;lastValidatedAt?:string|null;validationStatus?:string;lastSync:null};sprint:{name:string;startDate:string|null;finishDate:string|null;totalItems:number;completedItems:number;activeItems:number;progress:number;daysRemaining:number|null;health:string;calculatedAt:string}|null;relatedModules:{milestones:{available:boolean;reason:string};raid:{available:boolean;reason:string}};activity:Array<{action:string;source:string;correlationId:string;occurredAt:string}>;calculatedAt:string };

export function ProjectOverview({overview,loading,error,onClose,onRetry,onEdit}:{overview:Overview|null;loading:boolean;error:string;onClose:()=>void;onRetry:()=>void;onEdit:(project:Project)=>void}){
 const close=useRef<HTMLButtonElement>(null);useEffect(()=>{close.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[onClose]);
 return <div className="overview-backdrop" role="presentation"><aside className="overview-drawer" role="dialog" aria-modal="true" aria-labelledby="overview-title"><div className="overview-topbar"><div><span className="section-kicker">PROJECT OVERVIEW</span><h2 id="overview-title">{overview?.project.name??"Loading Project"}</h2>{overview&&<p>{overview.project.businessId} · {overview.project.productName}</p>}</div><button ref={close} onClick={onClose} aria-label="Close Project overview">×</button></div>
 {loading?<div className="module-state" role="status"><span className="loader"/>Loading Project overview…</div>:error?<div className="module-state error-state"><strong>Overview unavailable</strong><p>{error}</p><button onClick={onRetry}>Try again</button></div>:overview&&<div className="overview-content">
 <section className="overview-hero"><div><span className={`health-badge health-${overview.project.health.toLowerCase().replaceAll(" ","-")}`}>{overview.project.health}</span><span className="neutral-badge">{overview.project.status}</span><h3>{overview.project.objective||"No objective recorded"}</h3><p>{overview.project.description||"No Project description has been added."}</p></div><div className="overall-ring" style={{"--progress":`${overview.project.overallProgress*3.6}deg`} as React.CSSProperties}><strong>{overview.project.overallProgress}%</strong><span>Overall</span></div></section>
 <section className="overview-section"><div className="overview-section-title"><div><span className="section-kicker">DELIVERY MODEL</span><h3>Stage progress</h3></div><span>Calculated {formatDateTime(overview.calculatedAt)}</span></div><div className="overview-stages">{overview.stageProgress.map(s=><article key={s.stage}><div><strong>{label(s.stage)}</strong><span>{s.weight}% weight · {s.source}</span></div><b>{s.completion}%</b><div><i style={{width:`${s.completion}%`}}/></div><small>{s.weightedContribution.toFixed(1)}% contribution</small></article>)}</div></section>
 <section className="overview-grid"><article className="overview-card"><span className="section-kicker">DATES &amp; GOVERNANCE</span><dl><Row label="Start" value={formatDate(overview.project.startDate)}/><Row label="Target end" value={formatDate(overview.project.targetEndDate)}/><Row label="Sign-off" value={overview.project.signOffStatus}/><Row label="Release" value={overview.project.releaseStatus}/><Row label="Priority" value={overview.project.priority}/></dl></article><article className="overview-card"><span className="section-kicker">BUSINESS CONTEXT</span><dl><Row label="Product" value={`${overview.project.productName} · ${overview.project.productCode}`}/><Row label="Market" value={overview.project.market||"Not recorded"}/><Row label="Customer" value={overview.project.customer||"Not recorded"}/><Row label="Budget" value={overview.project.budgetAmount?`${overview.project.budgetCurrency} ${overview.project.budgetAmount.toLocaleString()}`:"Not recorded"}/></dl></article></section>
 <section className="overview-section overview-copy-grid"><article><span className="section-kicker">BUSINESS VALUE</span><p>{overview.project.businessValue||"Not recorded"}</p></article><article><span className="section-kicker">SCOPE</span><p>{overview.project.scope||"Not recorded"}</p></article><article><span className="section-kicker">OUT OF SCOPE</span><p>{overview.project.outOfScope||"Not recorded"}</p></article></section>
 <section className="overview-section"><div className="overview-section-title"><div><span className="section-kicker">ENGINEERING DELIVERY</span><h3>Integration &amp; current sprint</h3></div></div>{overview.delivery.connected?<div className="truth-panel compact"><span>↔</span><div><strong>{overview.delivery.provider} linked · {overview.delivery.azureProjectName}</strong><p>{overview.delivery.organization}{overview.delivery.azureTeamName?` / ${overview.delivery.azureTeamName}`:" / Whole Project"} · {overview.delivery.validationStatus?.replaceAll("_"," ")}</p></div></div>:<div className="truth-panel"><span>↔</span><div><strong>No engineering provider linked</strong><p>Configure a governed Azure Project mapping in Integrations.</p></div></div>}{overview.sprint?<div className="sprint-summary"><div><span>Current sprint</span><strong>{overview.sprint.name}</strong><small>{formatDate(overview.sprint.startDate)} – {formatDate(overview.sprint.finishDate)}</small></div><div><span>Completion</span><strong>{overview.sprint.progress}%</strong><small>{overview.sprint.completedItems} of {overview.sprint.totalItems} items</small></div><div><span>Time remaining</span><strong>{overview.sprint.daysRemaining===null?"Unknown":`${overview.sprint.daysRemaining}d`}</strong><small>{overview.sprint.activeItems} active</small></div><div><span>Health</span><strong>{overview.sprint.health.replaceAll("_"," ")}</strong><small>Refreshed {formatDateTime(overview.sprint.calculatedAt)}</small></div></div>:overview.delivery.connected&&<div className="truth-panel compact sprint-empty"><span>○</span><div><strong>No sprint snapshot</strong><p>{overview.delivery.azureTeamName?"Refresh the current sprint from Integrations.":"Add an Azure Team mapping to enable sprint metrics."}</p></div></div>}<div className="deferred-grid"><div><strong>Milestones</strong><span>{overview.relatedModules.milestones.reason}</span></div><div><strong>RAID</strong><span>{overview.relatedModules.raid.reason}</span></div></div></section>
 <section className="overview-section"><div className="overview-section-title"><div><span className="section-kicker">TRACEABILITY</span><h3>Recent activity</h3></div></div>{overview.activity.length?<ol className="activity-list">{overview.activity.map(a=><li key={a.correlationId+a.occurredAt}><span>{a.action.slice(0,1)}</span><div><strong>Project {a.action.toLowerCase()}</strong><p>{formatDateTime(a.occurredAt)} · {a.source}</p></div></li>)}</ol>:<div className="truth-panel compact"><span>○</span><div><strong>No activity recorded</strong><p>Governed changes will appear here.</p></div></div>}</section>
 <div className="overview-actions"><button className="secondary-action" onClick={onClose}>Close</button><button className="primary-action" onClick={()=>onEdit(overview.project)}>Edit Project</button></div>
 </div>}</aside></div>;
}
function Row({label,value}:{label:string;value:string}){return <><dt>{label}</dt><dd>{value}</dd></>};
const label=(v:string)=>v.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase());
const formatDate=(v:string|null)=>v?new Date(`${v}T00:00:00`).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"}):"Not recorded";
const formatDateTime=(v:string)=>new Date(v.endsWith("Z")?v:`${v}Z`).toLocaleString(undefined,{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"});
