import { env } from "cloudflare:workers";
import { organizationUrl,type AzureConnectionInput } from "../app/integrations/azure-contract";

export type AzureConnectionRecord={id:string;name:string;organization:string;organizationUrl:string;authType:string;credentialBinding:string;status:string;syncFrequency:string;lastTestedAt:string|null;lastSuccessfulAt:string|null;lastErrorCode:string|null;lastErrorMessage:string|null;enabled:number;version:number;createdAt:string;updatedAt:string};
const columns=`id,name,organization,organization_url AS organizationUrl,auth_type AS authType,credential_binding AS credentialBinding,status,sync_frequency AS syncFrequency,last_tested_at AS lastTestedAt,last_successful_at AS lastSuccessfulAt,last_error_code AS lastErrorCode,last_error_message AS lastErrorMessage,enabled,version,created_at AS createdAt,updated_at AS updatedAt`;
export async function listAzureConnections(){const result=await env.DB.prepare(`SELECT ${columns} FROM azure_connections WHERE record_status='ACTIVE' ORDER BY name`).all<AzureConnectionRecord>();return result.results;}
export async function getAzureConnection(id:string){return env.DB.prepare(`SELECT ${columns} FROM azure_connections WHERE id=? AND record_status='ACTIVE'`).bind(id).first<AzureConnectionRecord>();}
export async function createAzureConnection(input:AzureConnectionInput,actor:string,correlationId:string){const id=crypto.randomUUID();await env.DB.batch([env.DB.prepare(`INSERT INTO azure_connections (id,name,organization,organization_url,auth_type,credential_binding,sync_frequency,enabled,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(id,input.name,input.organization,organizationUrl(input.organization),input.authType,input.credentialBinding,input.syncFrequency,input.enabled?1:0,actor,actor),env.DB.prepare(`INSERT INTO audit_logs (id,entity_type,entity_id,action,after_json,source,correlation_id) VALUES (?,?,?,?,?,'APPLICATION',?)`).bind(crypto.randomUUID(),"AzureConnection",id,"CREATE",JSON.stringify({name:input.name,organization:input.organization,authType:input.authType,credentialBinding:input.credentialBinding,syncFrequency:input.syncFrequency}),correlationId)]);return getAzureConnection(id);}
export async function recordConnectionTest(id:string,result:{ok:boolean;testedAt:string;errorCode?:string;message:string},correlationId:string){await env.DB.batch([env.DB.prepare(`UPDATE azure_connections SET status=?,last_tested_at=?,last_successful_at=CASE WHEN ?=1 THEN ? ELSE last_successful_at END,last_error_code=?,last_error_message=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND record_status='ACTIVE'`).bind(result.ok?"CONNECTED":"ERROR",result.testedAt,result.ok?1:0,result.testedAt,result.errorCode??null,result.ok?null:result.message,id),env.DB.prepare(`INSERT INTO audit_logs (id,entity_type,entity_id,action,after_json,source,correlation_id) VALUES (?,?,?,?,?,'AZURE_DEVOPS',?)`).bind(crypto.randomUUID(),"AzureConnection",id,"TEST_CONNECTION",JSON.stringify({ok:result.ok,errorCode:result.errorCode??null,testedAt:result.testedAt}),correlationId)]);return getAzureConnection(id);}
export function getCredential(binding:string){const value=(env as unknown as Record<string,unknown>)[binding];return typeof value==="string"&&value.length?value:null;}
