import { env } from "cloudflare:workers";
import type { CompletionDisposition } from "../app/delivery/sprint-lifecycle-contract";

type SprintRow = { id: string; projectId: string; origin: string; status: string; capacityHours: number; version: number };
type MemberRow = { id: string; backlogItemId: string; businessId: string; itemType: string; title: string; itemStatus: string; blocked: number; plannedPoints: number; plannedHours: number; sequence: number; unresolved: number };
const sprint = (id: string) => env.DB.prepare("SELECT id,project_id projectId,origin,status,capacity_hours capacityHours,version FROM sprints WHERE id=? AND record_status='ACTIVE'").bind(id).first<SprintRow>();
const members = (id: string) => env.DB.prepare("SELECT m.id,m.backlog_item_id backlogItemId,b.business_id businessId,b.item_type itemType,b.title,b.status itemStatus,b.blocked,m.planned_points plannedPoints,m.planned_hours plannedHours,m.sequence,(SELECT COUNT(*) FROM backlog_dependencies d JOIN backlog_items p ON p.id=d.predecessor_item_id WHERE d.successor_item_id=b.id AND d.dependency_type IN ('BLOCKS','REQUIRES') AND p.status<>'DONE') unresolved FROM sprint_memberships m JOIN backlog_items b ON b.id=m.backlog_item_id WHERE m.sprint_id=? AND m.removed_at IS NULL ORDER BY m.sequence").bind(id).all<MemberRow>();

export async function activateSprint(id: string, version: number, actor: string, correlationId: string) {
  const row = await sprint(id); if (!row) return { kind: "not_found" as const }; if (row.origin !== "LOCAL") return { kind: "read_only" as const }; if (row.status !== "PLANNED") return { kind: "wrong_status" as const }; if (row.version !== version) return { kind: "conflict" as const };
  if (await env.DB.prepare("SELECT id FROM sprints WHERE project_id=? AND origin='LOCAL' AND status='ACTIVE' AND record_status='ACTIVE' LIMIT 1").bind(row.projectId).first()) return { kind: "active_exists" as const };
  const result = await members(id), items = result.results; if (!items.length) return { kind: "empty" as const };
  if (items.some(item => item.itemStatus !== "READY" || item.blocked || item.unresolved > 0)) return { kind: "items_not_ready" as const };
  const hours = items.reduce((sum, item) => sum + item.plannedHours, 0), points = items.reduce((sum, item) => sum + item.plannedPoints, 0); if (hours > row.capacityHours) return { kind: "over_capacity" as const };
  const now = new Date().toISOString(), baselineId = crypto.randomUUID(), snapshot = items.map(item => ({ membershipId: item.id, backlogItemId: item.backlogItemId, businessId: item.businessId, plannedPoints: item.plannedPoints, plannedHours: item.plannedHours, sequence: item.sequence }));
  await env.DB.batch([
    env.DB.prepare("INSERT INTO sprint_baselines(id,sprint_id,item_count,committed_points,committed_hours,membership_snapshot_json,activated_at,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?)").bind(baselineId, id, items.length, points, hours, JSON.stringify(snapshot), now, actor, actor),
    env.DB.prepare("UPDATE sprints SET status='ACTIVE',activated_at=?,committed_points=?,version=version+1,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id=? AND version=? AND status='PLANNED'").bind(now, points, actor, id, version),
    ...items.map(item => env.DB.prepare("UPDATE backlog_items SET status='IN_PROGRESS',delivery_state='IN_PROGRESS',version=version+1,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id=? AND status='READY'").bind(actor, item.backlogItemId)),
    env.DB.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,after_json,actor_user_id,source,correlation_id) VALUES(?,?,?,?,?,?,'APPLICATION',?)").bind(crypto.randomUUID(), "Sprint", id, "ACTIVATE", JSON.stringify({ baselineId, itemCount: items.length, committedPoints: points, committedHours: hours, activatedAt: now }), actor, correlationId),
  ]);
  return { kind: "ok" as const, version: version + 1 };
}

export async function changeActiveScope(id: string, input: { action: "ADD" | "REMOVE"; reason: string; version: number; backlogItemId: string; membershipId: string }, actor: string, correlationId: string) {
  const row = await sprint(id); if (!row) return { kind: "not_found" as const }; if (row.origin !== "LOCAL") return { kind: "read_only" as const }; if (row.status !== "ACTIVE") return { kind: "wrong_status" as const }; if (row.version !== input.version) return { kind: "conflict" as const };
  if (input.action === "ADD") {
    const item = await env.DB.prepare("SELECT id,project_id projectId,origin,status,item_type itemType,blocked,COALESCE(story_points,0) points,COALESCE(estimate_hours,0) hours FROM backlog_items WHERE id=? AND record_status='ACTIVE'").bind(input.backlogItemId).first<{ id: string; projectId: string; origin: string; status: string; itemType: string; blocked: number; points: number; hours: number }>();
    if (!item) return { kind: "item_not_found" as const }; if (item.projectId !== row.projectId || item.origin !== "LOCAL") return { kind: "scope" as const }; if (item.status !== "READY" || item.blocked || !["STORY", "TASK", "BUG"].includes(item.itemType)) return { kind: "item_not_ready" as const };
    if (await env.DB.prepare("SELECT id FROM sprint_memberships WHERE sprint_id=? AND backlog_item_id=? LIMIT 1").bind(id, item.id).first()) return { kind: "already_assigned" as const };
    if (await env.DB.prepare("SELECT m.id FROM sprint_memberships m JOIN sprints s ON s.id=m.sprint_id WHERE m.backlog_item_id=? AND m.removed_at IS NULL AND s.status IN ('PLANNED','ACTIVE') AND s.record_status='ACTIVE'").bind(item.id).first()) return { kind: "already_assigned" as const };
    if (await env.DB.prepare("SELECT d.id FROM backlog_dependencies d JOIN backlog_items p ON p.id=d.predecessor_item_id WHERE d.successor_item_id=? AND d.dependency_type IN ('BLOCKS','REQUIRES') AND p.status<>'DONE' LIMIT 1").bind(item.id).first()) return { kind: "unresolved" as const };
    const next = await env.DB.prepare("SELECT COALESCE(MAX(sequence),0)+1 value FROM sprint_memberships WHERE sprint_id=?").bind(id).first<{ value: number }>(), membershipId = crypto.randomUUID();
    await env.DB.batch([env.DB.prepare("INSERT INTO sprint_memberships(id,sprint_id,backlog_item_id,planned_points,planned_hours,sequence,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?)").bind(membershipId, id, item.id, item.points, item.hours, next?.value ?? 1, actor, actor), env.DB.prepare("UPDATE backlog_items SET status='IN_PROGRESS',delivery_state='IN_PROGRESS',version=version+1,updated_by=? WHERE id=?").bind(actor, item.id), env.DB.prepare("UPDATE sprints SET committed_points=(SELECT COALESCE(SUM(planned_points),0) FROM sprint_memberships WHERE sprint_id=? AND removed_at IS NULL),version=version+1,updated_by=? WHERE id=? AND version=?").bind(id, actor, id, input.version), env.DB.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,after_json,actor_user_id,source,correlation_id) VALUES(?,?,?,?,?,?,'APPLICATION',?)").bind(crypto.randomUUID(), "Sprint", id, "ACTIVE_SCOPE_ADD", JSON.stringify({ membershipId, backlogItemId: item.id, reason: input.reason }), actor, correlationId)]);
  } else {
    const membership = await env.DB.prepare("SELECT id,backlog_item_id backlogItemId FROM sprint_memberships WHERE id=? AND sprint_id=? AND removed_at IS NULL").bind(input.membershipId, id).first<{ id: string; backlogItemId: string }>(); if (!membership) return { kind: "membership_not_found" as const };
    await env.DB.batch([env.DB.prepare("UPDATE sprint_memberships SET removed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id=?").bind(actor, membership.id), env.DB.prepare("UPDATE backlog_items SET status='READY',delivery_state='READY',version=version+1,updated_by=? WHERE id=? AND status<>'DONE'").bind(actor, membership.backlogItemId), env.DB.prepare("UPDATE sprints SET committed_points=(SELECT COALESCE(SUM(planned_points),0) FROM sprint_memberships WHERE sprint_id=? AND removed_at IS NULL),version=version+1,updated_by=? WHERE id=? AND version=?").bind(id, actor, id, input.version), env.DB.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,before_json,actor_user_id,source,correlation_id) VALUES(?,?,?,?,?,?,'APPLICATION',?)").bind(crypto.randomUUID(), "Sprint", id, "ACTIVE_SCOPE_REMOVE", JSON.stringify({ ...membership, reason: input.reason }), actor, correlationId)]);
  }
  return { kind: "ok" as const, version: input.version + 1 };
}

export async function completeSprint(id: string, version: number, dispositions: CompletionDisposition[], actor: string, correlationId: string) {
  const row = await sprint(id); if (!row) return { kind: "not_found" as const }; if (row.origin !== "LOCAL") return { kind: "read_only" as const }; if (row.status !== "ACTIVE") return { kind: "wrong_status" as const }; if (row.version !== version) return { kind: "conflict" as const };
  const current = (await members(id)).results, byId = new Map(dispositions.map(item => [item.membershipId, item])); if (current.length !== dispositions.length || new Set(dispositions.map(item => item.membershipId)).size !== current.length || current.some(item => !byId.has(item.id))) return { kind: "incomplete_dispositions" as const };
  const targets = new Map<string, { id: string; projectId: string; next: number }>();
  for (const member of current) { const disposition = byId.get(member.id)!; if (member.itemStatus === "DONE" && disposition.disposition !== "COMPLETED") return { kind: "completed_mismatch" as const }; if (member.itemStatus !== "DONE" && disposition.disposition === "COMPLETED") return { kind: "incomplete_mismatch" as const }; if (disposition.disposition === "CARRYOVER") { const target = await env.DB.prepare("SELECT id,project_id projectId FROM sprints WHERE id=? AND origin='LOCAL' AND status='PLANNED' AND record_status='ACTIVE'").bind(disposition.targetSprintId).first<{ id: string; projectId: string }>(); if (!target || target.projectId !== row.projectId || target.id === id) return { kind: "invalid_target" as const }; if (!targets.has(target.id)) { const next = await env.DB.prepare("SELECT COALESCE(MAX(sequence),0)+1 value FROM sprint_memberships WHERE sprint_id=?").bind(target.id).first<{ value: number }>(); targets.set(target.id, { ...target, next: next?.value ?? 1 }); } } }
  const statements = [], evidence = [] as Record<string, unknown>[];
  for (const member of current) { const disposition = byId.get(member.id)!, dispositionId = crypto.randomUUID(); let targetMembershipId: string | null = null; if (disposition.disposition === "CARRYOVER") { const target = targets.get(disposition.targetSprintId!)!; targetMembershipId = crypto.randomUUID(); statements.push(env.DB.prepare("INSERT INTO sprint_memberships(id,sprint_id,backlog_item_id,planned_points,planned_hours,sequence,carried_from_membership_id,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?)").bind(targetMembershipId, target.id, member.backlogItemId, member.plannedPoints, member.plannedHours, target.next++, member.id, actor, actor)); statements.push(env.DB.prepare("UPDATE backlog_items SET status='READY',delivery_state='READY',version=version+1,updated_by=? WHERE id=?").bind(actor, member.backlogItemId)); } else if (disposition.disposition === "BACKLOG") statements.push(env.DB.prepare("UPDATE backlog_items SET status='READY',delivery_state='READY',version=version+1,updated_by=? WHERE id=?").bind(actor, member.backlogItemId)); else if (disposition.disposition === "REMOVED") statements.push(env.DB.prepare("UPDATE backlog_items SET status='REMOVED',delivery_state='REMOVED',version=version+1,updated_by=? WHERE id=?").bind(actor, member.backlogItemId)); statements.push(env.DB.prepare("INSERT INTO sprint_completion_dispositions(id,sprint_id,membership_id,disposition,target_sprint_id,target_membership_id,reason,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?)").bind(dispositionId, id, member.id, disposition.disposition, disposition.targetSprintId, targetMembershipId, disposition.reason, actor, actor)); evidence.push({ membershipId: member.id, backlogItemId: member.backlogItemId, disposition: disposition.disposition, targetSprintId: disposition.targetSprintId, reason: disposition.reason }); }
  for (const target of targets.values()) statements.push(env.DB.prepare("UPDATE sprints SET committed_points=(SELECT COALESCE(SUM(planned_points),0) FROM sprint_memberships WHERE sprint_id=? AND removed_at IS NULL),version=version+1,updated_by=? WHERE id=?").bind(target.id, actor, target.id));
  const completedAt = new Date().toISOString(); statements.push(env.DB.prepare("UPDATE sprints SET status='COMPLETED',completed_at=?,version=version+1,updated_at=CURRENT_TIMESTAMP,updated_by=? WHERE id=? AND version=? AND status='ACTIVE'").bind(completedAt, actor, id, version)); statements.push(env.DB.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,after_json,actor_user_id,source,correlation_id) VALUES(?,?,?,?,?,?,'APPLICATION',?)").bind(crypto.randomUUID(), "Sprint", id, "COMPLETE", JSON.stringify({ completedAt, dispositions: evidence }), actor, correlationId)); await env.DB.batch(statements);
  return { kind: "ok" as const, version: version + 1, completedAt };
}
