import { env } from "cloudflare:workers";

type SprintEvidence = { id: string; businessId: string; projectId: string; projectName: string; name: string; origin: string; startDate: string; endDate: string; status: string; sourceRevision: string | null; syncedAt: string | null };
type MetricEvidence = { id: string; sourceOrigin: string; sourceRevision: string; plannedPoints: number; completedPoints: number; plannedItems: number; completedItems: number; remainingWork: number; bugCount: number; openBugCount: number; blockerCount: number; carryoverCount: number; carryoverPoints: number; elapsedDays: number; totalDays: number; progress: number; expectedProgress: number; health: string; completionMethod: string; numerator: number | null; denominator: number | null; formula: string; healthTolerancePercentage: number; blockerThreshold: number; zeroProgressDays: number; velocityLookback: number; calculatedAt: string };
type BurndownEvidence = { snapshotDate: string; plannedScope: number; remainingScope: number; completedScope: number; idealRemainingScope: number; scopeChange: number; sourceRevision: string; calculatedAt: string };
type VelocityEvidence = { sprintId: string; businessId: string; name: string; endDate: string; completedPoints: number; sourceRevision: string; calculatedAt: string };

export async function getSprintMetricEvidence(sprintId: string) {
  const sprint = await env.DB.prepare("SELECT s.id,s.business_id businessId,s.project_id projectId,p.name projectName,s.name,s.origin,s.start_date startDate,s.end_date endDate,s.status,s.source_revision sourceRevision,s.synced_at syncedAt FROM sprints s JOIN projects p ON p.id=s.project_id WHERE s.id=? AND s.record_status='ACTIVE'").bind(sprintId).first<SprintEvidence>();
  if (!sprint) return { kind: "not_found" as const };
  const metric = await env.DB.prepare("SELECT id,source_origin sourceOrigin,source_revision sourceRevision,planned_points plannedPoints,completed_points completedPoints,planned_items plannedItems,completed_items completedItems,remaining_work remainingWork,bug_count bugCount,open_bug_count openBugCount,blocker_count blockerCount,carryover_count carryoverCount,carryover_points carryoverPoints,elapsed_days elapsedDays,total_days totalDays,progress,expected_progress expectedProgress,health,completion_method completionMethod,numerator,denominator,formula,health_tolerance_percentage healthTolerancePercentage,blocker_threshold blockerThreshold,zero_progress_days zeroProgressDays,velocity_lookback velocityLookback,calculated_at calculatedAt FROM sprint_metric_snapshots WHERE sprint_id=? ORDER BY calculated_at DESC,id DESC LIMIT 1").bind(sprintId).first<MetricEvidence>();
  if (!metric) return { kind: "no_evidence" as const, sprint };
  const [burndown, velocity] = await Promise.all([
    env.DB.prepare("SELECT snapshot_date snapshotDate,planned_scope plannedScope,remaining_scope remainingScope,completed_scope completedScope,ideal_remaining_scope idealRemainingScope,scope_change scopeChange,source_revision sourceRevision,calculated_at calculatedAt FROM daily_burndown_snapshots WHERE sprint_id=? ORDER BY snapshot_date ASC,calculated_at ASC LIMIT 120").bind(sprintId).all<BurndownEvidence>(),
    env.DB.prepare("SELECT s.id sprintId,s.business_id businessId,s.name,s.end_date endDate,m.completed_points completedPoints,m.source_revision sourceRevision,m.calculated_at calculatedAt FROM sprints s JOIN sprint_metric_snapshots m ON m.sprint_id=s.id WHERE s.project_id=? AND s.origin=? AND s.status='COMPLETED' AND s.record_status='ACTIVE' AND NOT EXISTS(SELECT 1 FROM sprint_metric_snapshots newer WHERE newer.sprint_id=s.id AND (newer.calculated_at>m.calculated_at OR (newer.calculated_at=m.calculated_at AND newer.id>m.id))) ORDER BY s.end_date DESC,s.id DESC LIMIT ?").bind(sprint.projectId, sprint.origin, metric.velocityLookback).all<VelocityEvidence>(),
  ]);
  const velocitySeries = [...velocity.results].reverse(), velocityAverage = velocitySeries.length ? Math.round(velocitySeries.reduce((total, point) => total + point.completedPoints, 0) / velocitySeries.length * 10) / 10 : null;
  return { kind: "ok" as const, sprint, current: metric, burndown: burndown.results, velocity: { lookback: metric.velocityLookback, averageCompletedPoints: velocityAverage, series: velocitySeries }, source: { label: sprint.origin === "AZURE_DEVOPS" ? "Azure DevOps · read-only evidence" : "Command Center · local evidence", sourceRevision: metric.sourceRevision, calculatedAt: metric.calculatedAt } };
}
