"use client";

import { useCallback, useEffect, useState } from "react";

type Project = { id: string; name: string; code: string };
type Sprint = { id: string; businessId: string; projectId: string; projectName: string; projectCode: string; name: string; goal: string; origin: string; startDate: string; endDate: string; status: string; capacityHours: number; committedPoints: number; plannedHours: number; itemCount: number; version: number };
type Member = { id: string; backlogItemId: string; businessId: string; itemType: string; title: string; status: string; plannedPoints: number; plannedHours: number; blocked: boolean; unresolvedDependencies: number };
type Available = { id: string; businessId: string; itemType: string; title: string; status: string; storyPoints: number; estimateHours: number; blocked: boolean; unresolvedDependencies: number };
const empty = { projectId: "", name: "", goal: "", startDate: "", endDate: "", capacityHours: "0" };

export function SprintCenter({ canCreate, canPlan }: { canCreate: boolean; canPlan: boolean }) {
  const [sprints, setSprints] = useState<Sprint[]>([]), [projects, setProjects] = useState<Project[]>([]), [projectId, setProjectId] = useState(""), [status, setStatus] = useState(""), [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<Sprint | null>(null), [members, setMembers] = useState<Member[]>([]), [available, setAvailable] = useState<Available[]>([]);
  const [open, setOpen] = useState(false), [editing, setEditing] = useState<Sprint | null>(null), [form, setForm] = useState({ ...empty }), [errors, setErrors] = useState<Record<string, string>>({}), [saving, setSaving] = useState(false), [message, setMessage] = useState(""), [isError, setIsError] = useState(false);
  const load = useCallback(async () => { setLoading(true); const query = new URLSearchParams({ pageSize: "100" }); if (projectId) query.set("projectId", projectId); if (status) query.set("status", status); const [response, projectResponse] = await Promise.all([fetch(`/api/v2/sprints?${query}`), fetch("/api/v1/projects?pageSize=100&sort=name")]); const [body, projectBody] = await Promise.all([response.json(), projectResponse.json()]); setSprints(response.ok ? body.data ?? [] : []); if (projectResponse.ok) setProjects(projectBody.data ?? []); setLoading(false); }, [projectId, status]);
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, [load]);
  const showCreate = () => { setEditing(null); setForm({ ...empty, projectId: projectId || projects[0]?.id || "" }); setErrors({}); setOpen(true); };
  const showEdit = (sprint: Sprint) => { setEditing(sprint); setForm({ projectId: sprint.projectId, name: sprint.name, goal: sprint.goal, startDate: sprint.startDate, endDate: sprint.endDate, capacityHours: String(sprint.capacityHours) }); setErrors({}); setOpen(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setErrors({}); setMessage(""); setIsError(false); const payload = { ...form, capacityHours: Number(form.capacityHours), ...(editing ? { version: editing.version } : {}) }; const response = await fetch(editing ? `/api/v2/sprints/${editing.id}` : "/api/v2/sprints", { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) { setErrors(body.error?.validationDetails ?? {}); setMessage(body.error?.message ?? "Sprint could not be saved."); setIsError(true); } else { setOpen(false); setMessage(editing ? "Sprint plan updated." : "Planned Sprint created."); await load(); if (editing && selected?.id === editing.id) await openPlanner({ ...editing, ...payload, version: body.data.version }); } setSaving(false); };
  const openPlanner = async (sprint: Sprint) => { setMessage(""); setIsError(false); const response = await fetch(`/api/v2/sprints/${sprint.id}`), body = await response.json(); if (!response.ok) { setMessage(body.error?.message ?? "Sprint could not be opened."); setIsError(true); return; } setSelected(body.data.sprint); setMembers(body.data.memberships ?? []); setAvailable(body.data.available ?? []); };
  const refreshPlanner = async (version: number) => { if (!selected) return; const response = await fetch(`/api/v2/sprints/${selected.id}`), body = await response.json(); if (response.ok) { setSelected({ ...body.data.sprint, version }); setMembers(body.data.memberships ?? []); setAvailable(body.data.available ?? []); await load(); } };
  const assign = async (item: Available) => { if (!selected) return; const response = await fetch(`/api/v2/sprints/${selected.id}/items`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ backlogItemId: item.id, version: selected.version }) }), body = await response.json(); if (!response.ok) { setMessage(body.error?.message ?? "Item could not be assigned."); setIsError(true); return; } setMessage(`${item.businessId} added to the Sprint.`); setIsError(false); await refreshPlanner(body.data.version); };
  const remove = async (member: Member) => { if (!selected) return; const response = await fetch(`/api/v2/sprints/${selected.id}/items/${member.id}?version=${selected.version}`, { method: "DELETE" }), body = await response.json(); if (!response.ok) { setMessage(body.error?.message ?? "Item could not be removed."); setIsError(true); return; } setMessage(`${member.businessId} returned to the Backlog.`); setIsError(false); await refreshPlanner(body.data.version); };
  const move = async (index: number, direction: -1 | 1) => { if (!selected) return; const target = index + direction; if (target < 0 || target >= members.length) return; const ordered = [...members]; [ordered[index], ordered[target]] = [ordered[target], ordered[index]]; const response = await fetch(`/api/v2/sprints/${selected.id}/items`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ membershipIds: ordered.map(item => item.id), version: selected.version }) }), body = await response.json(); if (!response.ok) { setMessage(body.error?.message ?? "Sprint order could not be changed."); setIsError(true); return; } setMembers(ordered); setSelected({ ...selected, version: body.data.version }); setMessage("Sprint Backlog order saved."); setIsError(false); };
  const plannedHours = members.reduce((sum, item) => sum + item.plannedHours, 0), plannedPoints = members.reduce((sum, item) => sum + item.plannedPoints, 0);

  return <section className="sprint-center"><div className="portfolio-toolbar"><div><span className="section-kicker">LOCAL SPRINT PLANNING</span><h2>Sprint Portfolio <small>{sprints.length}</small></h2></div>{canCreate && <button className="primary-action" onClick={showCreate}>+ New Sprint</button>}</div>{message && <div className={isError ? "form-error" : "success-banner"} role="status">{message}</div>}<div className="filter-bar"><label><span className="sr-only">Project</span><select value={projectId} onChange={event => setProjectId(event.target.value)}><option value="">All Projects</option>{projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label><span className="sr-only">Sprint status</span><select value={status} onChange={event => setStatus(event.target.value)}><option value="">All statuses</option><option>PLANNED</option><option>ACTIVE</option><option>COMPLETED</option></select></label></div>
    {loading ? <div className="module-state"><span className="loader" />Loading Sprints…</div> : !sprints.length ? <div className="module-state empty-state"><strong>No local Sprints</strong><p>Create a Planned Sprint to establish dates, goal and team capacity.</p></div> : <div className="sprint-cards">{sprints.map(sprint => <article key={sprint.id}><header><span>{sprint.businessId} · {sprint.projectCode}</span><b>{sprint.status}</b></header><h3>{sprint.name}</h3><p>{sprint.goal}</p><dl><div><dt>Dates</dt><dd>{sprint.startDate} – {sprint.endDate}</dd></div><div><dt>Capacity</dt><dd>{sprint.plannedHours} / {sprint.capacityHours}h</dd></div><div><dt>Commitment</dt><dd>{sprint.committedPoints} pts · {sprint.itemCount} items</dd></div></dl><footer><button className="secondary-action" onClick={() => openPlanner(sprint)}>Open planner</button>{canPlan && sprint.origin === "LOCAL" && sprint.status === "PLANNED" && <button onClick={() => showEdit(sprint)}>Edit details</button>}</footer></article>)}</div>}
    {selected && <div className="sprint-planner"><header><div><span>{selected.businessId} · {selected.projectName}</span><h2>{selected.name}</h2><p>{selected.goal}</p></div><button onClick={() => setSelected(null)} aria-label="Close Sprint planner">×</button></header><div className="planner-metrics"><div><span>Capacity</span><strong>{plannedHours} / {selected.capacityHours}h</strong><small>{Math.max(0, selected.capacityHours - plannedHours)}h remaining</small></div><div><span>Story commitment</span><strong>{plannedPoints} points</strong><small>Hours and points remain separate</small></div><div><span>Sprint Backlog</span><strong>{members.length} items</strong><small>Ordered planning baseline</small></div></div><div className="planner-columns"><section><h3>Ready Backlog <small>{available.length}</small></h3>{!available.length ? <div className="planner-empty">No eligible Ready work.</div> : available.map(item => <article key={item.id}><div><span>{item.businessId} · {item.itemType}</span><strong>{item.title}</strong><small>{item.storyPoints || 0} pts · {item.estimateHours || 0}h{item.blocked ? " · Blocked" : ""}</small></div>{canPlan && selected.status === "PLANNED" && <button onClick={() => assign(item)} disabled={item.unresolvedDependencies > 0}>{item.unresolvedDependencies > 0 ? "Dependency unresolved" : "Add →"}</button>}</article>)}</section><section><h3>Sprint Backlog <small>{members.length}</small></h3>{!members.length ? <div className="planner-empty">Add Ready Stories, Tasks or Bugs.</div> : members.map((member, index) => <article key={member.id}><div><span>{member.businessId} · {member.itemType}</span><strong>{member.title}</strong><small>{member.plannedPoints} pts · {member.plannedHours}h{member.unresolvedDependencies ? ` · ${member.unresolvedDependencies} unresolved` : ""}</small></div>{canPlan && selected.status === "PLANNED" && <div className="planner-actions"><button onClick={() => move(index, -1)} disabled={index === 0}>↑</button><button onClick={() => move(index, 1)} disabled={index === members.length - 1}>↓</button><button onClick={() => remove(member)}>Remove</button></div>}</article>)}</section></div><div className="planner-deferred">Activation, baseline freezing, completion and carryover are authorized for Step 7.</div></div>}
    {open && <div className="dialog-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget && !saving) setOpen(false); }}><div className="product-dialog" role="dialog" aria-modal="true" aria-labelledby="sprint-form-title"><form onSubmit={save}><div className="dialog-header"><div><span className="section-kicker">PLANNED SPRINT</span><h2 id="sprint-form-title">{editing ? "Edit Sprint" : "Create Sprint"}</h2></div><button type="button" onClick={() => setOpen(false)} aria-label="Close">×</button></div><div className="form-grid"><Field label="Project" error={errors.projectId}><select value={form.projectId} onChange={event => setForm(value => ({ ...value, projectId: event.target.value }))}><option value="">Select Project</option>{projects.map(project => <option key={project.id} value={project.id}>{project.name} · {project.code}</option>)}</select></Field><Field label="Sprint name" error={errors.name}><input value={form.name} onChange={event => setForm(value => ({ ...value, name: event.target.value }))} /></Field><Field label="Sprint goal" error={errors.goal} wide><textarea rows={3} value={form.goal} onChange={event => setForm(value => ({ ...value, goal: event.target.value }))} /></Field><Field label="Start date" error={errors.startDate}><input type="date" value={form.startDate} onChange={event => setForm(value => ({ ...value, startDate: event.target.value }))} /></Field><Field label="End date" error={errors.endDate}><input type="date" value={form.endDate} onChange={event => setForm(value => ({ ...value, endDate: event.target.value }))} /></Field><Field label="Capacity hours" error={errors.capacityHours}><input type="number" min="0" value={form.capacityHours} onChange={event => setForm(value => ({ ...value, capacityHours: event.target.value }))} /></Field></div>{isError && message && <div className="form-error" role="alert">{message}</div>}<div className="dialog-actions"><button type="button" className="secondary-action" onClick={() => setOpen(false)}>Cancel</button><button className="primary-action" disabled={saving}>{saving ? "Saving…" : editing ? "Save Sprint" : "Create Planned Sprint"}</button></div></form></div></div>}
  </section>;
}

function Field({ label, error, wide, children }: { label: string; error?: string; wide?: boolean; children: React.ReactNode }) { return <label className={wide ? "field wide" : "field"}><span>{label}</span>{children}{error && <small role="alert">{error}</small>}</label>; }
